on: push

name: Doc tests

jobs:
  documentation-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run unit tests on unix
        run: cargo test --release --doc