on:
  push:
    branches:
      - main

name: Release build

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Unix release build
        run: cargo build --release

      - uses: actions/upload-artifact@v6
        with:
          name: example-build
          path: ./target/release/rust-project-template
          retention-days: 10
          if-no-files-found: warn
